# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADfJV90FjrC3_rghsbgJzSDybnWDg_2K
"""

!pip install transformers datasets evaluate scikit-learn

from transformers import pipeline

classifier = pipeline("text-classification")

print(classifier("I really loved this movie."))
print(classifier("This was boring and disappointing."))

from datasets import load_dataset
ds= load_dataset("mltrev23/financial-sentiment-analysis")

ds

for i in range(5):
    print(ds["train"][i])

set(ds["train"]["Sentiment"])

split_ds = ds["train"].train_test_split(test_size=0.2, seed=42)
split_ds

from transformers import AutoTokenizer
tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased")

tokenised_ds=split_ds.rename_column("Sentiment","labels")

label2id = {"negative": 0,"neutral": 1,"positive": 2}
id2label = {v: k for k, v in label2id.items()}

def change_labels(example):
    example["labels"] = label2id[example["labels"]]
    return example

def tokenize_sentences(example):
  return tokenizer(example["Sentence"],truncation=True)

new_ds=tokenised_ds.map(change_labels)
tokenised_ds=new_ds.map(tokenize_sentences,batched=True)

tokenised_ds

from transformers import DataCollatorWithPadding
data_collator=DataCollatorWithPadding(tokenizer=tokenizer)

print(tokenised_ds["train"][0])

tf_ready_ds = tokenised_ds.remove_columns(["Sentence"])

print(tf_ready_ds["train"][0])

from transformers import AutoModelForSequenceClassification
checkpoint = "distilbert-base-uncased"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=3)

import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average="weighted"
    )
    acc = accuracy_score(labels, predictions)
    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

from transformers import TrainingArguments
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_steps=50
)

from transformers import Trainer
trainer=Trainer(model=model,
    args=training_args,
    train_dataset=tokenised_ds["train"],
    eval_dataset=tokenised_ds["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics)

trainer.train()

trainer.evaluate()

from transformers import pipeline
classifier = pipeline("text-classification",model=trainer.model,tokenizer=tokenizer)

samples=[
    "The company reported strong quarterly profits.",
    "It is a bad day for stock market.",
    "Investors are uncertain about future growth."
]

for text in samples:
    print(text)
    print(classifier(text))
    print()